# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-22 02:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.director.model_func.jsonfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(blank=True, max_length=200, verbose_name='key')),
                ('kind', models.CharField(blank=True, max_length=100, verbose_name='\u79cd\u7c7b')),
                ('detail', models.TextField(blank=True, verbose_name='\u8be6\u7ec6')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u64cd\u4f5c\u8005')),
            ],
        ),
        migrations.CreateModel(
            name='PermitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='\u6743\u9650\u540d\u79f0')),
                ('permit', helpers.director.model_func.jsonfield.JsonField(default={}, verbose_name='\u7528\u6237\u6743\u9650')),
                ('desp', models.TextField(blank=True, verbose_name='\u63cf\u8ff0')),
                ('group', models.ManyToManyField(blank=True, null=True, to='auth.Group', verbose_name='\u7528\u6237\u7ec4')),
            ],
        ),
    ]
