# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-07 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(blank=True, max_length=30, verbose_name='\u5458\u5de5\u53f7'),
        ),
    ]
