# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-08 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0003_departmanage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmanage',
            name='recv_event',
            field=models.CharField(blank=True, choices=[('work', '\u5de5\u4f5c\u5ba1\u6838'), ('small_money', '\u5c0f\u989d\u82b1\u8d39')], max_length=500, verbose_name='recive pop event'),
        ),
    ]
