# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-17 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0004_auto_20170608_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='follow_depart',
            field=models.ManyToManyField(blank=True, null=True, related_name='follow', to='organize.Department', verbose_name='followed department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manage_depart',
            field=models.ManyToManyField(blank=True, null=True, related_name='manage', to='organize.Department', verbose_name='managed department'),
        ),
    ]
