# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-18 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0005_auto_20170617_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='follow_depart',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='manage_depart',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='depart',
        ),
        migrations.AddField(
            model_name='employee',
            name='depart',
            field=models.ManyToManyField(blank=True, null=True, to='organize.Department', verbose_name='department'),
        ),
    ]
