# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-18 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('organize', '0006_auto_20170618_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPermitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organize.Department', verbose_name='department')),
                ('emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organize.Employee', verbose_name='employee')),
                ('group', models.ManyToManyField(blank=True, null=True, to='auth.Group', verbose_name='\u7ec4')),
            ],
        ),
    ]
