# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-30 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import helpers.director.model_validator


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0009_auto_20170622_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '\u96c7\u5458\u4fe1\u606f'},
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='id_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u8eab\u4efd\u8bc1\u53f7\u7801'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u7535\u8bdd\u53f7\u7801'),
        ),
        migrations.AlterField(
            model_name='departmanage',
            name='depart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organize.Department', verbose_name='\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='departmanage',
            name='recv_event',
            field=models.CharField(blank=True, max_length=500, verbose_name='\u63a5\u53d7\u4e8b\u4ef6'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='new department', max_length=500, validators=[helpers.director.model_validator.has_str], verbose_name='\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='department',
            name='par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='organize.Department', verbose_name='\u4e0a\u7ea7'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='depart',
            field=models.ManyToManyField(blank=True, null=True, to='organize.Department', verbose_name='\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='content',
            field=models.TextField(blank=True, verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='emp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organize.Employee', verbose_name='\u5458\u5de5'),
        ),
        migrations.AlterField(
            model_name='workpermitmodel',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organize.Department', verbose_name='\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='workpermitmodel',
            name='emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organize.Employee', verbose_name='\u5458\u5de5'),
        ),
    ]
