# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-16 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0010_auto_20170630_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='id_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u8eab\u4efd\u8bc1'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='emp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organize.Employee', verbose_name='\u96c7\u5458'),
        ),
        migrations.AlterField(
            model_name='workpermitmodel',
            name='emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organize.Employee', verbose_name='\u96c7\u5458'),
        ),
    ]
