# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-23 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0012_concerndepartmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='id_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u8eab\u4efd\u8bc1\u53f7'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u7535\u8bdd\u53f7\u7801'),
        ),
    ]
