# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-22 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KVModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=500, verbose_name='key')),
                ('value', models.TextField(blank=True, verbose_name='value')),
                ('editor_type', models.CharField(choices=[('blocktext', '\u666e\u901a\u7f16\u8f91\u5668'), ('richtext', '\u5bcc\u6587\u672c\u7f16\u8f91\u5668')], default='blocktext', max_length=30, verbose_name='\u7f16\u8f91\u5668\u7c7b\u578b')),
            ],
        ),
    ]
