# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-21 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0008_employeedata'),
        ('work', '0002_auto_20170616_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organize.Department', verbose_name='\u4ece\u5c5e\u90e8\u95e8'),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='sub_type',
            field=models.CharField(choices=[('normal', '\u666e\u901a'), ('importent', '\u91cd\u8981')], default='normal', max_length=50, verbose_name='\u63d0\u4ea4\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='check_depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_workrecord', to='organize.Department', verbose_name='\u5ba1\u6838\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.Work', verbose_name='\u5de5\u65f6\u540d\u79f0'),
        ),
    ]
