# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-20 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0011_auto_20170716_1842'),
        ('work', '0005_auto_20170630_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='checker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_workrecord', to='organize.Employee', verbose_name='\u5ba1\u6838\u4eba'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
