# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-16 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_daka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dakarecord',
            name='pos',
            field=models.CharField(blank=True, max_length=100, verbose_name='position'),
        ),
    ]
