# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-16 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='check_depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organize.Department', verbose_name='\u5ba1\u6838\u90e8\u95e8'),
        ),
    ]
