# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-30 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20170622_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='sub_type',
            field=models.CharField(choices=[('normal_work', '\u666e\u901a\u5de5\u4f5c'), ('importent_work', '\u91cd\u8981\u5de5\u4f5c')], default='normal_work', max_length=50, verbose_name='\u63d0\u4ea4\u7c7b\u578b'),
        ),
    ]
