# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.director.model_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='\u540d\u79f0')),
                ('age', models.CharField(blank=True, max_length=50, verbose_name='\u5e74\u9f84')),
                ('head', models.CharField(blank=True, default='/static/res/image/user.jpg', max_length=200, verbose_name='\u5934\u50cf')),
                ('id_number', models.CharField(blank=True, max_length=200, verbose_name='\u8eab\u4efd\u8bc1')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='\u5730\u5740')),
                ('gen', models.CharField(blank=True, choices=[('male', '\u7537'), ('femal', '\u5973')], max_length=30, verbose_name='\u6027\u522b')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='\u7535\u8bdd')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='new department', max_length=500, validators=[helpers.director.model_validator.has_str], verbose_name='department name')),
                ('detail', models.TextField(blank=True, verbose_name='\u8be6\u7ec6')),
                ('par_chain', models.CharField(blank=True, max_length=200, verbose_name='parent chain')),
                ('par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='organize.Department', verbose_name='parent department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(default='', max_length=30, verbose_name='\u5458\u5de5\u53f7')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='\u804c\u4f4d')),
                ('baseinfo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organize.BasicInfo', verbose_name='\u57fa\u672c\u4fe1\u606f')),
                ('depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organize.Department', verbose_name='department')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8d26\u53f7')),
            ],
            options={
                'verbose_name': 'Employee Info',
            },
        ),
    ]
