# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-08 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0002_auto_20170607_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recv_event', models.CharField(blank='{}', max_length=500, verbose_name='recive pop event')),
                ('depart', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organize.Department', verbose_name='department')),
            ],
        ),
    ]
