# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-22 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0008_employeedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmanage',
            name='recv_event',
            field=models.CharField(blank=True, choices=[('normal_work', '\u666e\u901a\u5de5\u4f5c'), ('importent_work', '\u91cd\u8981\u5de5\u4f5c')], max_length=500, verbose_name='recive pop event'),
        ),
    ]
