# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-18 05:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organize', '0011_auto_20170716_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcernDepartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departs', models.ManyToManyField(blank=True, null=True, to='organize.Department', verbose_name='\u90e8\u95e8')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8d26\u53f7')),
            ],
        ),
    ]
