# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-22 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import helpers.director.model_validator


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0013_auto_20170823_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicinfo',
            options={'verbose_name': '\u5458\u5de5\u57fa\u672c\u4fe1\u606f\u8868'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '\u90e8\u95e8\u4fe1\u606f\u8868'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '\u5458\u5de5\u5de5\u4f5c\u4fe1\u606f\u8868'},
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='new department', max_length=500, validators=[helpers.director.model_validator.has_str], verbose_name='\u90e8\u95e8\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='department',
            name='par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='organize.Department', verbose_name='\u4e0a\u7ea7\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='emp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organize.Employee', verbose_name='\u5458\u5de5'),
        ),
        migrations.AlterField(
            model_name='workpermitmodel',
            name='emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organize.Employee', verbose_name='\u5458\u5de5'),
        ),
    ]
