
page_dc = {
    "kv"	:"<class 'helpers.common.admin.KvTablePage'>",
    "kv.edit"	:"<class 'helpers.common.admin.KvFormPage'>",
    "del_rows"	:"<class 'helpers.director.fields.delpage.DelPage'>",
    "log"	:"<class 'helpers.director.log.logpage.LogPage'>",
    "user"	:"<class 'helpers.director.admin.UserTablePage'>",
    "user.edit"	:"<class 'helpers.director.admin.UserFormPage'>",
    "group"	:"<class 'helpers.director.admin.GroupTablePage'>",
    "group.edit"	:"<class 'helpers.director.admin.GroupFormPage'>",
    "permit.edit"	:"<class 'helpers.director.admin.PermitFormPage'>",
    "group_human"	:"<class 'helpers.director.admin.GroupGroup'>",
    "group_human.edit"	:"<class 'helpers.director.access.assem_group.AssemGroupPage'>",
    "jb_user"	:"<class 'helpers.case.jb_admin.admin.UserPage'>",
    "jb_group"	:"<class 'helpers.case.jb_admin.admin.GroupPage'>",
    
    "matches"	:"<class 'maindb.matches.matches.MatchsPage'>",
    "tickets"	:"<class 'maindb.matches.ticket_master.TicketMasterPage'>",
    "matches_statistics"	:"<class 'maindb.matches.matches_statistics.MatchesStatisticsPage'>",
    "ChargeFlow"	:"<class 'maindb.money.chargeflow.ChargeFlowPage'>",
    
   
    "recharge"	:"<class 'maindb.money.recharge.RechargePage'>",
    "withdraw"	:"<class 'maindb.money.withdraw.WithdrawPage'>",
  
    "user_statistics"	:"<class 'maindb.report.user_statistics.UserStatisticsPage'>",
    
    # 会员管理
    "account"	:"<class 'maindb.member.account.AccountPage'>",    # 账号
    "balancelog"	:"<class 'maindb.money.balancelog.BalancelogPage'>", 
    "loginlog"	:"<class 'maindb.member.loginlog.LoginLogPage'>", # 登录日志
    "bankcards"	:"<class 'maindb.member.bankcard.BankCard'>",
    "ReleventUser"	:"<class 'maindb.member.relevent_user.ReleventUserPage'>", # 相关用户
    "chum_user"	:"<class 'maindb.member.chum_user.ChumUser'>", # 流失用户
    
    # 市场
    "banner"	:"<class 'maindb.marketing.banner.BannerPage'>",
    "app_package"	:"<class 'maindb.marketing.app_package.AppPackage'>",
    "notice"	:"<class 'maindb.marketing.notice.NoticePage'>",
    "agentnotice"	:"<class 'maindb.marketing.agent_notice.AgentNoticePage'>", # 代理公告
    "currency"	:"<class 'maindb.basic_data.currency.CurrencyPage'>",
    "agent_qa"	:"<class 'maindb.marketing.agent_qa.AgentQAPage'>", # 代理帮助
    "help"	:"<class 'maindb.marketing.help_center.HelpPage'>",
    "activity_v2"	:"<class 'maindb.marketing.active_v2.ActiviyV2Page'>", # 活动
    "feedback"	:"<class 'maindb.marketing.feedback.Feedback'>",
    "rankuser"	:"<class 'maindb.marketing.rank.RankUserPage'>",  # 虚拟用户
    "rank"	:"<class 'maindb.marketing.rank.RankPage'>",  # 虚拟排行
    "bonuspage"	:"<class 'maindb.marketing.bonus_dispatch.BonusPage'>",  # 红利发放
      
    "operation_log"	:"<class 'maindb.member.operation_log.OperationLog'>",  #  系统日志
   
    "maindb.TbOdds"	:"<class 'maindb.matches.odds.OddsPage'>",
    "basketball_matchs"	:"<class 'maindb.matches.basketball_matches.BasketMatchsPage'>",
    "BasketballMatchesStatisticsPage"	:"<class 'maindb.matches.basketball_matches_statistics.BasketballMatchesStatisticsPage'>",
    
   
    "activity"	:"<class 'maindb.marketing.activity.ActivityPage'>",  # X   老活动，废弃了。
    "app_resource"	:"<class 'maindb.basic_data.app_resource.AppResource'>",
   
    "blackip_range"	:"<class 'maindb.riskcontrol.black_users.BlackIPRangeListPage'>",
    "white_ips"	:"<class 'maindb.riskcontrol.black_users.WhiteIpListPage'>",
    "white_users"	:"<class 'maindb.riskcontrol.black_users.WhiteUserListPage'>",
  
 
  
    "maindb.report.channel"	:"<class 'maindb.report.report_channel.ReportChnnel'>",
    "platform_profit"	:"<class 'maindb.report.platform_profit.PlatformProfit'>",
    "recharge_reports"	:"<class 'maindb.report.recharge_report.RechargeReport'>",
    "everyday_report"	:"<class 'maindb.report.every_day.EveryDayReportPage'>",
    "bet_analysis"	:"<class 'maindb.report.bet_analysis.BetAnalysisPage'>",
    "bet_type"	:"<class 'maindb.basic_data.bet_type.BetTypePage'>",
    
    # 联赛页面
    "league"	:"<class 'maindb.basic_data.league.League'>",
    "teams"	:"<class 'maindb.basic_data.teams.TeamsPage'>",
    "banktypes"	:"<class 'maindb.basic_data.banktypes.BankTypesPage'>",
    "paychannel"	:"<class 'maindb.basic_data.paychannel.PayChannelPage'>",
    "sportstype"	:"<class 'maindb.basic_data.sporttype.SportsTypesPage'>",
    "teams_basketball"	:"<class 'maindb.basic_data.teams_basketball.TeamBasketballPage'>",
    "LeagueGroupPage"	:"<class 'maindb.riskcontrol.admin_league_group.LeagueGroupPage'>",
    "ParameterPage"	:"<class 'maindb.riskcontrol.admin_parameter.ParameterPage'>",
    "sourececontrol"	:"<class 'maindb.riskcontrol.sourcecontral.SourceControlPage'>",
    "Paychannelblackaccount"	:"<class 'maindb.riskcontrol.paychannel_blackaccount.PaychannelblackaccountPage'>",
    "limitusergroup"	:"<class 'maindb.riskcontrol.limitusergroup.LimitUserGroupPage'>",
    "RiskcontrolSetting"	:"<class 'maindb.riskcontrol.riskcontrol_setting.RiskcontrolSetting'>",
    "withdraw_limit"	:"<class 'maindb.riskcontrol.withdraw_limit.WithdrawLimitPage'>",
    "paychannel_blackip"	:"<class 'maindb.riskcontrol.paychannel_blackiprange.PayChannelBlackIPRangeList'>",
    "area_blacklist"	:"<class 'maindb.riskcontrol.area_blacklist.AreaBlackList'>",
    "paychannel_area_blacklist"	:"<class 'maindb.riskcontrol.paychannel_area_blacklist.PayChannelAreaBlackList'>",
    "white_ip_rangelist"	:"<class 'maindb.riskcontrol.white_ip_rangelist.WhiteIPRangeList'>",
    "vip_paychannel"	:"<class 'maindb.money.vip_paychannel.VIPPayChannelPage'>",
    "agent_user"	:"<class 'maindb.admin_agent.agentuser.AgentUser'>",
    "agent_commission"	:"<class 'maindb.admin_agent.agent_commission.AgentCommission'>",
    "parameterinfo"	:"<class 'maindb.riskcontrol.new_withdraw_limit.WithDrawLimitContralPage'>",
    "marketgroup"	:"<class 'maindb.programer.marketgroup.MarketGroupPage'>",
    "marketpage"	:"<class 'maindb.programer.market.MarketPage'>",
    "usermarket"	:"<class 'maindb.programer.market.UserMarketPage'>",
    "outcome"	:"<class 'maindb.programer.outcome.OutcomePage'>",
    "home"	:"<class 'hello.admin.Home'>",
}


director = {
    "get_row"	:"function: get_row",
    "save_rows"	:"function: save_rows",
    "permit.programer"	:"<class 'helpers.director.admin.PermitPage.PermitTable'>",
    "permit.programer.edit"	:"<class 'helpers.director.admin.PermitFormPage.PermitForm'>",
    "jb_user"	:"<class 'helpers.case.jb_admin.admin.UserPage.tableCls'>",
    "jb_user.edit"	:"<class 'helpers.case.jb_admin.admin.UserFields'>",
    "jb_group"	:"<class 'helpers.case.jb_admin.admin.GroupPage.tableCls'>",
    "jb_group.edit"	:"<class 'helpers.case.jb_admin.admin.GroupForm'>",
    "authuser.regist"	:"<class 'helpers.authuser.admin_regist.RegistFormPage.fieldsCls'>",
    "do_login"	:"function: do_login",
    
    "cloudfile_uploader"	:"<class 'maindb.cus_models_fields.CloudFileUploader'>",
    "match.quit_ticket"	:"function: quit_ticket",
    "PeriodScoreTab"	:"<class 'maindb.matches.matches.PeriodScoreTab'>",
    "match.livescout_status"	:"function: match_livescout_status",
    "match.add_livescout"	:"function: add_livescout",
    "get_special_bet_value"	:"function: getSpecialbetValue",
    "save_special_bet_value"	:"function: save_special_bet_value_proc",
    "get_match_outcome_info"	:"function: get_match_outcome_info",
    "out_com_save"	:"function: out_com_save",
    "notify_match_recommend"	:"function: notify_match_recommend",
    "match.table"	:"<class 'maindb.matches.matches.MatchsPage.tableCls'>",
    "match.table.edit"	:"<class 'maindb.matches.matches.MatchForm'>",
    "outcome_tab"	:"<class 'maindb.matches.matches.OutcomeTab'>",
    "TbLivescout.table"	:"<class 'maindb.matches.matches.TbLivescoutTable'>",
    "games.ticketmaster"	:"<class 'maindb.matches.ticket_master.TicketMasterPage.tableCls'>",
    "games.ticketmaster.edit"	:"<class 'maindb.matches.ticket_master.TicketMasterForm'>",
    "games.TicketstakeTable"	:"<class 'maindb.matches.ticket_master.TicketstakeTable'>",
    "games.TicketparlayTable"	:"<class 'maindb.matches.ticket_master.TicketparlayTable'>",
    "games.ticketstake.matchform"	:"<class 'maindb.matches.ticket_master.MatchForm'>",
    "match.viewbymatch"	:"<class 'maindb.matches.matches_statistics.MatchesStatisticsPage.tableCls'>",
    "DetailStatistic"	:"<class 'maindb.matches.matches_statistics.DetailStatistic'>",
    "match_statistic.ticket_master"	:"<class 'maindb.matches.matches_statistics.TickmasterTab'>",
    "match_statistic.ticket_master.edit"	:"<class 'maindb.matches.ticket_master.TicketMasterForm'>",
    "ChargeFlow"	:"<class 'maindb.money.chargeflow.ChargeFlowPage.tableCls'>",
    "money.balancelog"	:"<class 'maindb.money.balancelog.BalancelogPage.tableCls'>",
    "BankCards"	:"<class 'maindb.member.bankcard.BankCard.tableCls'>",
    "BankCards.edit"	:"<class 'maindb.member.bankcard.BankCardForm'>",
    "Recharge"	:"<class 'maindb.money.recharge.RechargePage.tableCls'>",
    "Recharge.edit"	:"<class 'maindb.money.recharge.ConfirmRechargeForm'>",
    "has_audit_ticketmaster"	:"function: has_audit_ticketmaster",
    "tab.ticketmaster"	:"<class 'maindb.money.withdraw.TicketmasterTab'>",
    "Withdraw"	:"<class 'maindb.money.withdraw.WithdrawPage.tableCls'>",
    "Withdraw.edit"	:"<class 'maindb.money.withdraw.WithDrawForm'>",
    "account.loginpage"	:"<class 'maindb.member.loginlog.LoginLogPage.tableCls'>",
    "UserStatisticsPage"	:"<class 'maindb.report.user_statistics.UserStatisticsPage.tableCls'>",
    "account"	:"<class 'maindb.member.account.AccountPage.tableCls'>",
    "account.edit"	:"<class 'maindb.member.account.AccoutBaseinfo'>",
    "account.base.edit"	:"<class 'maindb.member.account.AccoutBaseinfo'>",
    "account.amount.edit"	:"<class 'maindb.member.account.AccoutModifyAmount'>",
    "account.betfullmodify"	:"<class 'maindb.member.account.ModifyBetFullRecord'>",
    "account.bankcard"	:"<class 'maindb.member.account.UserBankCard'>",
    "account.bankcard.edit"	:"<class 'maindb.member.bankcard.BankCardForm'>",
    "account.UserRecharge"	:"<class 'maindb.member.account.UserRecharge'>",
    "account.UserWithdraw"	:"<class 'maindb.member.account.UserWithdraw'>",
    "account.log"	:"<class 'maindb.member.account.AccountLoginTable'>",
    "account.ticketmaster"	:"<class 'maindb.member.account.AccountTicketTable'>",
    "account.balancelog"	:"<class 'maindb.member.account.AccountBalanceTable'>",
    "account.statistc"	:"<class 'maindb.member.account.UserStatisticsTab'>",
    "account.matches_statistics"	:"<class 'maindb.member.account.MatchesStatisticsTab'>",
    "account.betfullrecordtab"	:"<class 'maindb.member.account.BetFullRecordTab'>",
    "OperationLog"	:"<class 'maindb.member.operation_log.OperationLog.tableCls'>",
    "OperationLog.edit"	:"<class 'maindb.member.operation_log.OperationLogForm'>",
    "ReleventUser"	:"<class 'maindb.member.relevent_user.ReleventUserPage.tableCls'>",
    "chum_user"	:"<class 'maindb.member.chum_user.ChumUser.tableCls'>",
    "maindb.OddsTypeGroup4Table"	:"<class 'maindb.matches.odds.OddsTypeGroup4Table'>",
    "maindb.typegroup_2"	:"<class 'maindb.matches.odds.OddsTypeGroup2Table'>",
    "basketball.manul_outcome"	:"<class 'maindb.matches.basketball_matches.BasketOutcome'>",
    "basketball_matchs"	:"<class 'maindb.matches.basketball_matches.BasketMatchsPage.tableCls'>",
    "basketball_matchs.edit"	:"<class 'maindb.matches.basketball_matches.BasketMatchForm'>",
    "BasketballMatchesStatisticsPage"	:"<class 'maindb.matches.basketball_matches_statistics.BasketballMatchesStatisticsPage.tableCls'>",
    "BasketballDetailStatistic"	:"<class 'maindb.matches.basketball_matches_statistics.BasketballDetailStatistic'>",
    "banner.table"	:"<class 'maindb.marketing.banner.BannerPage.tableCls'>",
    "banner.table.edit"	:"<class 'maindb.marketing.banner.BannerForm'>",
    "gen_notice_static"	:"function: gen_notice_static",
    "notice.table"	:"<class 'maindb.marketing.notice.NoticePage.tableCls'>",
    "notice.table.edit"	:"<class 'maindb.marketing.notice.NoticeForm'>",
    "currency.table"	:"<class 'maindb.basic_data.currency.CurrencyPage.tableCls'>",
    "currency.table.edit"	:"<class 'maindb.basic_data.currency.CurrencyForm'>",
    "help.table"	:"<class 'maindb.marketing.help_center.HelpPage.tableCls'>",
    "help.table.edit"	:"<class 'maindb.marketing.help_center.HelpForm'>",
    "get_mtype_options"	:"function: _fun",
    "gen_help_static_file"	:"function: gen_help_static_file",
    "update_activity_file"	:"function: update_activity_file",
    "activity.table"	:"<class 'maindb.marketing.activity.ActivityPage.tableCls'>",
    "activity.table.edit"	:"<class 'maindb.marketing.activity.ActiveForm'>",
    "AppResource"	:"<class 'maindb.basic_data.app_resource.AppResource.tableCls'>",
    "AppResource.edit"	:"<class 'maindb.basic_data.app_resource.AppResourceForm'>",
    "app_pkg"	:"<class 'maindb.marketing.app_package.AppPackage.tableCls'>",
    "app_pkg.edit"	:"<class 'maindb.marketing.app_package.AppPackageForm'>",
    "agentnotice"	:"<class 'maindb.marketing.agent_notice.AgentNoticePage.tableCls'>",
    "agentnotice.edit"	:"<class 'maindb.marketing.agent_notice.NoticeForm'>",
    "update_activity_file_v2"	:"function: update_activity_file_v2",
    "activity_v2"	:"<class 'maindb.marketing.active_v2.ActiviyV2Page.tableCls'>",
    "activity_v2.edit"	:"<class 'maindb.marketing.active_v2.ActivityV2Form'>",
    "activity_v2.setting"	:"<class 'maindb.marketing.active_v2.ActivitySettingTable'>",
    "activity_v2.setting.edit"	:"<class 'maindb.marketing.active_v2.ActivitySettingForm'>",
    "rankuser"	:"<class 'maindb.marketing.rank.RankUserPage.tableCls'>",
    "rankuser.edit"	:"<class 'maindb.marketing.rank.RankUserForm'>",
    "rank"	:"<class 'maindb.marketing.rank.RankPage.tableCls'>",
    "rank.edit"	:"<class 'maindb.marketing.rank.RankForm'>",
    "risk.WhiteIpListPage"	:"<class 'maindb.riskcontrol.black_users.WhiteIpListPage.tableCls'>",
    "risk.WhiteIpListPage.edit"	:"<class 'maindb.riskcontrol.black_users.WhiteIPForm'>",
    "risk.WhiteuserlistPage"	:"<class 'maindb.riskcontrol.black_users.WhiteUserListPage.tableCls'>",
    "risk.WhiteuserlistPage.edit"	:"<class 'maindb.riskcontrol.black_users.WhiteUserForm'>",
    "risk.AccountSelect"	:"<class 'maindb.riskcontrol.black_users.AccountSelect'>",
    "risk.BlankipRangeListPage"	:"<class 'maindb.riskcontrol.black_users.BlackIPRangeListPage.tableCls'>",
    "risk.BlankipRangeListPage.edit"	:"<class 'maindb.riskcontrol.black_users.BlackIPRangeForm'>",
    "bonuslog_list"	:"<class 'maindb.marketing.bonus_dispatch.BonuslogTable'>",
    "bonuslog_list.edit"	:"<class 'maindb.marketing.bonus_dispatch.BonuslogForm'>",
    "bonustype"	:"<class 'maindb.marketing.bonus_dispatch.BonusTypeTable'>",
    "bonustype.edit"	:"<class 'maindb.marketing.bonus_dispatch.BonusTypeForm'>",
    "feedback.table"	:"<class 'maindb.marketing.feedback.Feedback.tableCls'>",
    "feedback.table.edit"	:"<class 'maindb.marketing.feedback.FeedbackForm'>",
    "agent_qa"	:"<class 'maindb.marketing.agent_qa.AgentQAPage.tableCls'>",
    "agent_qa.edit"	:"<class 'maindb.marketing.agent_qa.AgentQAForm'>",
    "maindb.report.channel"	:"<class 'maindb.report.report_channel.ReportChnnel.tableCls'>",
    "platform_profit"	:"<class 'maindb.report.platform_profit.PlatformProfit.tableCls'>",
    "recharge_reports"	:"<class 'maindb.report.recharge_report.RechargeReport.tableCls'>",
    "everyday_report"	:"<class 'maindb.report.every_day.EveryDayReportPage.tableCls'>",
    "WinbetRatio"	:"<class 'maindb.report.bet_analysis.WinbetRatio'>",
    "LoginNumer"	:"<class 'maindb.report.bet_analysis.LoginNumer'>",
    "BetCondition"	:"<class 'maindb.report.bet_analysis.BetCondition'>",
    "BetWeekChart"	:"<class 'maindb.report.bet_analysis.BetWeekChart'>",
    "MarketAnalysis"	:"<class 'maindb.report.bet_analysis.MarketAnalysis'>",
    "TournamentAnalysis"	:"<class 'maindb.report.bet_analysis.TournamentAnalysis'>",
    "maindb.TbOddstypeGroupPage"	:"<class 'maindb.basic_data.bet_type.BetTypePage.tableCls'>",
    "maindb.TbOddstypeGroupPage.edit"	:"<class 'maindb.basic_data.bet_type.BetTypeForm'>",
    "match.league"	:"<class 'maindb.basic_data.league.League.tableCls'>",
    "match.league.edit"	:"<class 'maindb.basic_data.league.LeagueForm'>",
    "maindb.teams"	:"<class 'maindb.basic_data.teams.TeamsPage.tableCls'>",
    "maindb.teams.edit"	:"<class 'maindb.basic_data.teams.TeamsFields'>",
    "league-options"	:"function: getLeagueOptions",
    "contry-options"	:"function: getCountry",
    "banktypes"	:"<class 'maindb.basic_data.banktypes.BankTypesPage.tableCls'>",
    "banktypes.edit"	:"<class 'maindb.basic_data.banktypes.BankTypesForm'>",
    "paychannel"	:"<class 'maindb.basic_data.paychannel.PayChannelPage.tableCls'>",
    "paychannel.edit"	:"<class 'maindb.basic_data.paychannel.PayChannelForm'>",
    "sportstype"	:"<class 'maindb.basic_data.sporttype.SportsTypesPage.tableCls'>",
    "sportstype.edit"	:"<class 'maindb.basic_data.sporttype.SportsTypeForm'>",
    "basketball-contry-options"	:"function: getCountry",
    "basketball-league-options"	:"function: getLeagueOptions",
    "teams_basketball"	:"<class 'maindb.basic_data.teams_basketball.TeamBasketballPage.tableCls'>",
    "teams_basketball.edit"	:"<class 'maindb.basic_data.teams_basketball.TeamsBasketballFields'>",
    "league_group.league_options"	:"function: league_options",
    "LeagueGroupPage"	:"<class 'maindb.riskcontrol.admin_league_group.LeagueGroupPage.tableCls'>",
    "LeagueGroupPage.edit"	:"<class 'maindb.riskcontrol.admin_league_group.LeagueGroupForm'>",
    "LeagueidInGroupForm"	:"<class 'maindb.riskcontrol.admin_league_group.LeagueidInGroupForm'>",
    "LeagueGroupSpreadForm"	:"<class 'maindb.riskcontrol.admin_league_group.LeagueGroupSpreadForm'>",
    "ParameterForm"	:"<class 'maindb.riskcontrol.admin_parameter.ParameterPage.fieldsCls'>",
    "sourececontrol"	:"<class 'maindb.riskcontrol.sourcecontral.SourceControlPage.tableCls'>",
    "sourececontrol.edit"	:"<class 'maindb.riskcontrol.sourcecontral.SoureceControlForm'>",
    "Paychannelblackaccount"	:"<class 'maindb.riskcontrol.paychannel_blackaccount.PaychannelblackaccountPage.tableCls'>",
    "Paychannelblackaccount.edit"	:"<class 'maindb.riskcontrol.paychannel_blackaccount.PaychannelblackaccountForm'>",
    "limitusergroup"	:"<class 'maindb.riskcontrol.limitusergroup.LimitUserGroupPage.tableCls'>",
    "limitusergroup.edit"	:"<class 'maindb.riskcontrol.limitusergroup.LimitUserForm'>",
    "RiskcontrolSetting"	:"<class 'maindb.riskcontrol.riskcontrol_setting.RiskcontrolSetting.tableCls'>",
    "RiskcontrolForm"	:"<class 'maindb.riskcontrol.riskcontrol_setting.RiskcontrolForm'>",
    "withdraw_limit"	:"<class 'maindb.riskcontrol.withdraw_limit.WithdrawLimitPage.fieldsCls'>",
    "PayChannelBlackIPRangeList"	:"<class 'maindb.riskcontrol.paychannel_blackiprange.PayChannelBlackIPRangeList.tableCls'>",
    "PayChannelBlackIPRangeList.edit"	:"<class 'maindb.riskcontrol.paychannel_blackiprange.PayChannelBlackIPRangeForm'>",
    "AreaBlackList"	:"<class 'maindb.riskcontrol.area_blacklist.AreaBlackList.tableCls'>",
    "AreaBlackList.edit"	:"<class 'maindb.riskcontrol.area_blacklist.AreaBlackListForm'>",
    "PayChannelAreaBlackList"	:"<class 'maindb.riskcontrol.paychannel_area_blacklist.PayChannelAreaBlackList.tableCls'>",
    "PayChannelAreaBlackList.edit"	:"<class 'maindb.riskcontrol.paychannel_area_blacklist.PayChannelAreaBlackListForm'>",
    "WhiteIPRangeList"	:"<class 'maindb.riskcontrol.white_ip_rangelist.WhiteIPRangeList.tableCls'>",
    "WhiteIPRangeList.edit"	:"<class 'maindb.riskcontrol.white_ip_rangelist.WhiteIPRangeForm'>",
    "ChargeType"	:"<class 'maindb.money.vip_paychannel.VIPPayChannelPage.tableCls'>",
    "ChargeType.edit"	:"<class 'maindb.money.vip_paychannel.ChargeTypeForm'>",
    "get_no_relation_vip_level"	:"function: get_left_vip_options",
    "YongJingForm"	:"<class 'maindb.admin_agent.agentuser.YongJingForm'>",
    "agent.parentselect"	:"<class 'maindb.admin_agent.agentuser.ParentSelect'>",
    "agent.ParentForm"	:"<class 'maindb.admin_agent.agentuser.ParentForm'>",
    "AgentUser"	:"<class 'maindb.admin_agent.agentuser.AgentUser.tableCls'>",
    "new_AgentUser"	:"<class 'maindb.admin_agent.agentuser.NewAgentUserForm'>",
    "agent_commission"	:"<class 'maindb.admin_agent.agent_commission.AgentCommission.tableCls'>",
    "agent_commission.audit"	:"function: audit",
    "agent_commission.onekey_all"	:"function: onekey_audit_all",
    "parameterinfo"	:"<class 'maindb.riskcontrol.new_withdraw_limit.WithDrawLimitContralPage.tableCls'>",
    "parameterinfo.edit"	:"<class 'maindb.riskcontrol.new_withdraw_limit.WithDrawForm'>",
    "marketgroup"	:"<class 'maindb.programer.marketgroup.MarketGroupPage.tableCls'>",
    "marketgroup.edit"	:"<class 'maindb.programer.marketgroup.MarketGroupForm'>",
    "Marketgroupwithmarket"	:"<class 'maindb.programer.marketgroup.MarketgroupwithmarketTable'>",
    "Marketgroupwithmarket.edit"	:"<class 'maindb.programer.marketgroup.MarketgroupwithmarketForm'>",
    "get_market_options"	:"function: get_market_options",
    "marketpage"	:"<class 'maindb.programer.market.MarketPage.tableCls'>",
    "marketpage.edit"	:"<class 'maindb.programer.market.MarketForm'>",
    "usermarket"	:"<class 'maindb.programer.market.UserMarketPage.tableCls'>",
    "usermarket.edit"	:"<class 'maindb.programer.market.UserMarketForm'>",
    "outcome"	:"<class 'maindb.programer.outcome.OutcomePage.tableCls'>",
    "outcome.edit"	:"<class 'maindb.programer.outcome.OutcomeForm'>",
    "trend_data"	:"function: trend_data",
}
=========2019-06-15 17:31:17.898325==========
