# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-15 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='name')),
                ('temp', models.CharField(blank=True, max_length=300, verbose_name='template')),
                ('label', models.CharField(blank=True, max_length=300, verbose_name='label')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='status')),
                ('content', models.TextField(blank=True, verbose_name='content')),
            ],
        ),
    ]
