# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-17 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_daka', '0004_auto_20170716_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='dakarecord',
            name='device',
            field=models.CharField(blank=True, max_length=300, verbose_name='device'),
        ),
    ]
